services:

  client-dev:
    build:
      context: .
      dockerfile: apps/client/Dockerfile.dev
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV = development
    depends_on:
      - server