FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml nx.json pnpm-workspace.yaml tsconfig.base.json eslint.config.mjs ./

RUN pnpm install

COPY apps/server ./apps/server

EXPOSE 3000

CMD [ "pnpm", "nx", "serve", "server", "--configuration=development" ]