FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml nx.json pnpm-workspace.yaml tsconfig.base.json eslint.config.mjs ./

RUN pnpm install

COPY apps/client ./apps/client

EXPOSE 4200

CMD [ "pnpm", "nx", "serve", "client", "--configuration=development" ]