name: Publish Proto Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@vaahe"

      - name: Install PNPM
        run: npm install -g pnpm@10.17.1

      - name: Cache PNPM
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-

      - name: Install dependencies
        run: npx pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Cache NX build
        uses: actions/cache@v3
        with:
          path: |
            dist
            node_modules/.cache/nx
          key: nx-build-${{ github.sha }}
          restore-keys: |
            nx-build-

      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Generate Typescript files from proto
        run: npx pnpm proto:generate

      - name: Build proto library
        run: npx pnpm nx build proto

      - name: Publish to Github Packages
        run: |
          cd libs/proto
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > .npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Cleanup .npmrc
        run: rm -f ~/.npmrc
